name: build-and-deploy

on:
  push:
    branches:
      - main
    paths:
      - "APPO.Backend/**"
      - ".github/workflows/main_appo-backend.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        working-directory: APPO.Backend
        run: dotnet restore

      - name: Build
        working-directory: APPO.Backend
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        working-directory: APPO.Backend
        run: dotnet publish APPO.Backend.csproj -c Release -o publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: appo-backend
          path: APPO.Backend/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download
