# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy Backend (.NET 8)

on:
  push:
    branches: [ main ]

# Opt into Node.js 24 for GitHub Actions internal runtime
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore
        working-directory: APPO.Backend

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: APPO.Backend

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish
        working-directory: APPO.Backend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
    
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8FAF967860724979858ED9381E300B74 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4750CCAD59DA478B9C16DB5AF36BD18D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_16B4DC17CFFA4FAE808053FCAF5702A5 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'appo-backend'
          slot-name: 'Production'
          package: .
          
